force-app/main/default/objects/Ambassador__c/Ambassador__c.object-meta.xml
<CustomObject>
    <label>Ambassador</label>
    <nameField>
        <label>Ambassador Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ambassadors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Ambassador__c/fields/Ambassador_Email__c.field-meta.xml
<CustomField>
    <fullName>Ambassador_Email__c</fullName>
    <label>Ambassador Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Ambassador__c/fields/OTP__c.field-meta.xml
<CustomField>
    <fullName>OTP__c</fullName>
    <label>Password</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Ambassador__c/fields/Roles__c.field-meta.xml
<CustomField>
    <fullName>Roles__c</fullName>
    <label>Roles</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>President and CEO</fullName>
            </value>
            <value>
                <fullName>Chief Placemaking Officer</fullName>
            </value>
            <value>
                <fullName>Public Safety Manger</fullName>
            </value>
            <value>
                <fullName>Public Space Operations Manager</fullName>
            </value>
            <value>
                <fullName>Ranger Captain</fullName>
            </value>
            <value>
                <fullName>Chief Economic Development Officer</fullName>
            </value>
            <value>
                <fullName>Economic Development Specialist</fullName>
            </value>
            <value>
                <fullName>Chief Marketing Officer</fullName>
            </value>
            <value>
                <fullName>Marketing &amp; Communications Specialist</fullName>
            </value>
            <value>
                <fullName>Program Manager</fullName>
            </value>
            <value>
                <fullName>Assistant Manager</fullName>
            </value>
            <value>
                <fullName>Director of Public &amp; External Affairs</fullName>
            </value>
            <value>
                <fullName>District360</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FSA_LoginPageRest_Class_Test.cls
/**************************************************************************************
* Class Name			: FSA_LoginPage_RestClass_Test                       Cc -91%.
* Created Date			: 19th Sep, 2024	
* Created By			: Buvaneswari P
* Class Description		: Test class for Custom API	using Login page.	
* Last modified by		: 
***************************************************************************************/
@isTest
public class FSA_LoginPageRest_Class_Test {
    @TestSetup 
    public static void setupData(){
        Ambassador__c amb = new Ambassador__c(Name='Charlie',Ambassador_Email__c='charlie@gmail.com',OTP__c='cha1',Active__c=True); 
        insert amb; 
        Ambassador__c amb1 = new Ambassador__c(Name='Charlie1',Ambassador_Email__c='charlie1@gmail.com',OTP__c='ch24',Active__c=True );
        insert amb1;
        Ambassador__c amb2 = new Ambassador__c(Name='Charlie2',Ambassador_Email__c='charlie2@gmail.com',OTP__c='cha5',Active__c=True );
        insert amb2;
        Ambassador__c amb3 = new Ambassador__c(Name='',Ambassador_Email__c='',OTP__c='',Active__c=True );
        insert amb3;
    }
    public static testmethod void getAmbassador_Test(){
        list<Ambassador__c> getRec =[Select id,Name,Ambassador_Email__c,OTP__c,Roles__c From Ambassador__c];
        System.assertEquals(getRec.size() , 4);
        String JsonMsg=JSON.serialize(getRec[0]);
        system.debug('####AmbList-->JsonMsg--> '+JsonMsg);
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueof(JsonMsg);      
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        FSA_LoginPage_RestClass.getAmbassador();
        Test.stopTest();
    }
     public static testmethod void error_Test(){
        list<Ambassador__c> getRec =[Select id,Name,Ambassador_Email__c,OTP__c,Roles__c From Ambassador__c];
        System.assertEquals(getRec.size() , 4);
        String JsonMsg=JSON.serialize(getRec[3]);
        system.debug('####AmbList-->JsonMsg--> '+JsonMsg);
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();             
        req.httpMethod = 'GET';
        req.requestBody = Blob.valueof(JsonMsg);      
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        FSA_LoginPage_RestClass.getAmbassador();
        Test.stopTest();
    }
}